name: 'PR Label Prompt'

on:
  pull_request:
    branches:
      - main
    types: [opened]
jobs:
  add_comment:
    name: 'Prompt for versioning label'
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: Please set a release label of either `major`, `minor`, `patch`, or `skip-release` to the pull request.
